# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc28e0bffa116a57e3731ce300bbffebc70fca9f159e6651029be4e12b084daf188025ba84cf1de334c462f8bd10319acb0cf7a55117cfb47463c3135b0d7183

test:
  secret_key_base: 3abc28b135a440cdc979ccdfafd48f9e7d7bdbf43ef01592b023816a0e851eea4cf864a7e6848f078547569de51a34a5c9dd722d09aef269261f18f74d1ce26a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
